module.exports = [
  // ===== CORE / ABS (15) =====
  "3_4_Sit-Up",
  "Ab_Crunch_Machine",
  "Ab_Roller",
  "Cable_Crunch",
  "Plank",
  "Hanging_Leg_Raise",
  "Russian_Twist",
  "Dead_Bug",
  "Bicycle_Crunch",
  "Jackknife_Sit-Up",
  "Sit-Up",
  "Reverse_Crunch",
  "Weighted_Crunches",
  "Toe_Touchers",
  "Flutter_Kicks",

  // ===== CHEST (15) =====
  "Barbell_Bench_Press_-_Medium_Grip",
  "Dumbbell_Bench_Press",
  "Incline_Dumbbell_Press",
  "Decline_Dumbbell_Bench_Press",
  "Wide-Grip_Barbell_Bench_Press",
  "Machine_Bench_Press",
  "Cable_Chest_Press",
  "Cable_Crossover",
  "Pushups",
  "Push-Up_Wide",
  "Close-Grip_Push-Up_off_of_a_Dumbbell",
  "Dips_-_Chest_Version",
  "Chest_Push_single_response",
  "Flat_Bench_Cable_Flyes",
  "Bodyweight_Flyes",

  // ===== BACK (18) =====
  "Barbell_Deadlift",
  "Romanian_Deadlift",
  "Bent_Over_Barbell_Row",
  "One-Arm_Dumbbell_Row",
  "Seated_Cable_Rows",
  "Lat_Pulldown",
  "Wide-Grip_Lat_Pulldown",
  "Chin-Up",
  "Pullups",
  "Inverted_Row",
  "Face_Pull",
  "Straight-Arm_Pulldown",
  "Rack_Pulls",
  "Back_Extension",
  "Hyperextensions_Back_Extensions",
  "T-Bar_Row_with_Handle",
  "V-Bar_Pulldown",
  "Upright_Barbell_Row",

  // ===== SHOULDERS (15) =====
  "Barbell_Shoulder_Press",
  "Dumbbell_Shoulder_Press",
  "Arnold_Dumbbell_Press",
  "Seated_Dumbbell_Press",
  "Standing_Military_Press",
  "Lateral_Raise_-_With_Bands",
  "Side_Lateral_Raise",
  "Front_Dumbbell_Raise",
  "Rear_Delt_Fly",
  "Cable_Shoulder_Press",
  "Face_Pull",
  "Upright_Cable_Row",
  "Smith_Machine_Overhead_Shoulder_Press",
  "Handstand_Push-Ups",
  "Bradford_Rocky_Presses",

  // ===== ARMS (BICEPS + TRICEPS) (20) =====
  "Barbell_Curl",
  "EZ-Bar_Curl",
  "Dumbbell_Bicep_Curl",
  "Hammer_Curls",
  "Concentration_Curls",
  "Preacher_Curl",
  "Cable_Preacher_Curl",
  "Spider_Curl",
  "Zottman_Curl",
  "Close-Grip_Barbell_Bench_Press",
  "EZ-Bar_Skullcrusher",
  "Triceps_Pushdown",
  "Triceps_Pushdown_-_Rope_Attachment",
  "Overhead_Triceps",
  "Bench_Dips",
  "Dips_-_Triceps_Version",
  "Lying_Triceps_Press",
  "Cable_Lying_Triceps_Extension",
  "Standing_Dumbbell_Triceps_Extension",
  "Tate_Press",

  // ===== LEGS / GLUTES (22) =====
  "Barbell_Squat",
  "Front_Barbell_Squat",
  "Goblet_Squat",
  "Leg_Press",
  "Hack_Squat",
  "Romanian_Deadlift",
  "Stiff-Legged_Barbell_Deadlift",
  "Walking_Lunge",
  "Bodyweight_Walking_Lunge",
  "Dumbbell_Lunges",
  "Step-up_with_Knee_Raise",
  "Bulgarian_Split_Squat",
  "Hip_Thrust",
  "Barbell_Glute_Bridge",
  "Glute_Ham_Raise",
  "Leg_Extensions",
  "Lying_Leg_Curls",
  "Standing_Calf_Raises",
  "Seated_Calf_Raise",
  "Donkey_Calf_Raises",
  "Weighted_Squat",
  "Box_Squat",

  // ===== CONDITIONING / CARDIO (10) =====
  "Battling_Ropes",
  "Jumping_Jacks",
  "Burpee",
  "Mountain_Climbers",
  "Air_Bike",
  "Rowing_Stationary",
  "Running_Treadmill",
  "Jogging_Treadmill",
  "Rope_Jumping",
  "Stairmaster"
];
